#!/usr/bin/env bash
# Writes src/backend/.env for one installation from the cloud template, with the
# production overrides, and creates its MySQL database + user in tydal-infra.
# Secrets are generated here; nothing is printed. Copy next to the
# installation's compose.yml and set the three values below.
#   ./make-env.sh
set -euo pipefail
NAME=pro                                  # short name: database/user tydal_NAME, prefixes
URL=https://tydal.example.org             # public address (scheme + host)
INFRA=/srv/tydal-infra                    # folder with infra.compose.yml + its .env

cd "$(dirname "$0")"
ENV=src/backend/.env
[ -f "$ENV" ] && { echo "$ENV exists — not overwriting"; exit 1; }
umask 077
cp src/tools/deploy/env.templates/backend.env.aicloud "$ENV"
. "$INFRA/.env"                           # MYSQL_ROOT_PASSWORD, REDIS_PASSWORD
DB_PASS=$(openssl rand -hex 24)
set_env() {  # key value — replace the line if present, else append
  local k="$1" v="$2"
  if grep -qE "^$k=" "$ENV"; then
    KEY="$k" VAL="$v" perl -i -pe 's/^\Q$ENV{KEY}\E=.*/$ENV{KEY}=$ENV{VAL}/' "$ENV"
  else
    printf '%s=%s\n' "$k" "$v" >> "$ENV"
  fi
}
set_env APP_ENV production
set_env APP_DEBUG false
set_env APP_URL "$URL"
set_env TYDAL_PUBLIC_URL "$URL"
set_env SANCTUM_STATEFUL_DOMAINS "${URL#*://}"
set_env LOG_LEVEL warning
set_env DB_HOST mysql
set_env DB_DATABASE "tydal_$NAME"
set_env DB_USERNAME "tydal_$NAME"
set_env DB_PASSWORD "$DB_PASS"
set_env REDIS_HOST redis
set_env REDIS_PASSWORD "$REDIS_PASSWORD"
# What keeps installations apart on the shared services:
set_env REDIS_PREFIX "tydal_${NAME}_"
set_env CACHE_PREFIX "tydal_${NAME}_cache_"
set_env SESSION_COOKIE "tydal_${NAME}_session"
set_env ELASTICSEARCH_INDEX_PREFIX "${NAME}_"
set_env TIKA_HOST http://tika:9998
set_env ELASTICSEARCH_HOST http://elasticsearch:9200
# The app port is published on 127.0.0.1 only: the host's nginx is its one peer.
set_env TRUSTED_PROXIES '*'
set_env TYDAL_SUPERADMIN_PASSWORD ''      # generated by the seeder
set_env AI_DEBUG false
docker exec -i -e MYSQL_PWD="$MYSQL_ROOT_PASSWORD" tydal-infra-mysql-1 mysql -uroot <<SQL
CREATE DATABASE IF NOT EXISTS tydal_$NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'tydal_$NAME'@'%' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON tydal_$NAME.* TO 'tydal_$NAME'@'%';
FLUSH PRIVILEGES;
SQL
echo "env written, database tydal_$NAME ready — fill in the AI keys in $ENV if you use AI"
