<?php

namespace App\Enums;

/**
 * Where the tag's label came from.
 *
 * Pairs with TagReviewer (who approved the entry). Together they replace the
 * old free-form `source` column on semantic_tags.
 */
enum TagVocabulary: string
{
    case ORGANIZATION = 'organization';   // Curated by the org (their own private vocabulary)
    case USER = 'user';           // Ad-hoc label coined by an end user
    case AI_GENERATED = 'ai_generated';   // Generated by Aity
    case TAXONOMY = 'taxonomy';       // Pulled from a controlled vocabulary (reserved)

    public function label(): string
    {
        return match ($this) {
            self::ORGANIZATION => 'Organization',
            self::USER => 'User',
            self::AI_GENERATED => 'AI Generated',
            self::TAXONOMY => 'Taxonomy',
        };
    }
}
